// <auto-generated />
using System;
using ArkadeHeroes.Server.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArkadeHeroes.Server.Persistence.Migrations
{
    [DbContext(typeof(GameStateDbContext))]
    [Migration("20260731174241_AppendOnlyAuditLog")]
    partial class AppendOnlyAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ArkadeHeroes.Server.Persistence.PersistedAuditEvent", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("ActorPlayerId");

                    b.HasIndex("DedupKey")
                        .IsUnique()
                        .HasFilter("\"DedupKey\" IS NOT NULL");

                    b.HasIndex("EventType");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("ArkadeHeroes.Server.Persistence.PersistedAuditSubject", b =>
                {
                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("AuditEventSubjects");
                });

            modelBuilder.Entity("ArkadeHeroes.Server.Persistence.PersistedFancyFind", b =>
                {
                    b.Property<string>("HeroId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Edition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UnixSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeroId");

                    b.ToTable("FancyFinds");
                });

            modelBuilder.Entity("ArkadeHeroes.Server.Persistence.PersistedHero", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("BreedCooldownUntil")
                        .HasColumnType("TEXT");

                    b.Property<int>("BreedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntropyHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("GauntletCooldownUntil")
                        .HasColumnType("TEXT");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenomeHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MintArkTxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentAId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentBId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerNonce")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerSeedHex")
                        .HasColumnType("TEXT");

                    b.Property<long>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("ArkadeHeroes.Server.Persistence.PersistedItemPurchase", b =>
                {
                    b.Property<string>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryTxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceId");

                    b.ToTable("ItemPurchases");
                });

            modelBuilder.Entity("ArkadeHeroes.Server.Persistence.PersistedOffer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AskSats")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemAssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ListingFeeSats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OfferAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OfferValueSats")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RefundAfterUnixSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("ArkadeHeroes.Server.Persistence.PersistedPlayer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastClaimDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginPubKeyHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("StarterClaimed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StarterFeeInvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StreakCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("TermsAcceptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TermsAcceptedVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ArkadeHeroes.Server.Persistence.PersistedStudProposal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Accepted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BreedFeeInvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<long>("BreedFeeSats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChildHeroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitmentHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Declined")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProposerHeroId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposerPlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ServerSeed")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("StudFeeInvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StudFeePaid")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StudFeeSats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudHeroId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudOwnerPlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StudProposals");
                });

            modelBuilder.Entity("ArkadeHeroes.Server.Persistence.PersistedTournament", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("BuyInSats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommitmentHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntrantsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenerPlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ServerSeed")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("ArkadeHeroes.Server.Persistence.PersistedTreasuryFlow", b =>
                {
                    b.Property<string>("Direction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Direction", "Id");

                    b.ToTable("TreasuryFlows");
                });

            modelBuilder.Entity("ArkadeHeroes.Server.Persistence.PersistedAuditSubject", b =>
                {
                    b.HasOne("ArkadeHeroes.Server.Persistence.PersistedAuditEvent", "Event")
                        .WithMany("Subjects")
                        .HasForeignKey("Sequence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ArkadeHeroes.Server.Persistence.PersistedAuditEvent", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
