<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ArkadeHeroes.Core\ArkadeHeroes.Core.csproj" />
    <ProjectReference Include="..\..\external\dotnet-sdk\NArk\NArk.csproj" />
    <ProjectReference Include="..\..\external\dotnet-sdk\NArk.Storage.EfCore\NArk.Storage.EfCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
